Support for ansible_ssh_extra_args and ANSIBLE_SSH_EXECUTABLE

diff --git a/ansible-ssh b/ansible-ssh
--- a/ansible-ssh
+++ b/ansible-ssh
@@ -1,53 +1,63 @@
 #!/bin/bash
+#set -x
 debug=/bin/true
-
-if [ $# -eq 0 ]; then
-    echo "Usage: $(basename $0) hostname <ssh arguments>"
-    exit 1
-fi
-
-host="$1"
-# All other arguments are ssh arguments
-shift
 
 for program in ansible-config ansible-inventory jq; do
     which "$program" > /dev/null || { echo "ERROR: not found: $program"; exit 1; }
 done
 
-ssh_args=$(ansible-config dump | grep '^ANSIBLE_SSH_ARGS' | cut -d'=' -f2-)
-$debug && echo "ssh_args: $ssh_args"
-inventory=$(ansible-inventory --list)
-# jq magic: https://stedolan.github.io/jq/manual/
-# .[] array/object value iterator
-# | combines two filters feeding output of left one into input of right one
-# .hosts? produces content of hosts key, no error if it does not exist
-# .[]? array/object value iterator, no error if output of . is not array or object (for example, it is null)
-all_hosts=$(echo "$inventory" | jq '.[] | .hosts? | .[]? ' | sort | uniq)
+if [ $# -eq 0 ]; then
+    echo "Usage: $(basename $0) hostname <ssh arguments>"
+    echo "Avaliable hosts:"
+    # jq magic: https://stedolan.github.io/jq/manual/
+    # .[] array/object value iterator
+    # | combines two filters feeding output of left one into input of right one
+    # .hosts? produces content of hosts key, no error if it does not exist
+    # .[]? array/object value iterator, no error if output of . is not array or object (for example, it is null)
+    ansible-inventory --list | jq '.[] | .hosts? | .[]? ' | sort | uniq
+    exit 1
+fi
 
-echo "$all_hosts" | grep -q "$host" || { echo "ERROR: $host not found in ansible inventory"; exit 1; }
+ssh_args=$(ansible-config dump | grep '^ANSIBLE_SSH_ARGS' | cut -d'=' -f2-)
+ssh_executable=$(ansible-config dump | grep '^ANSIBLE_SSH_EXECUTABLE' | cut -d'=' -f2-)
+$debug && echo "ssh_args: $ssh_args"
+$debug && echo "ssh_executable: $ssh_executable"
+
+host="$1"
+# All other arguments are ssh arguments
+shift
+
+inventory=$(ansible-inventory --host "$host")
+if [ $? -ne 0 ]; then
+    echo "ERROR: ansible inventory failed to gather info on $host"
+    exit 1
+fi
 
 # As of ansible 2.0, new style options like ansible_host override old style ansible_ssh_*
-# Except ansible_ssh_common_args
-ansible_ssh_host=$(echo "$inventory" | jq " ._meta.hostvars[\"$host\"].ansible_ssh_host? " | grep -v '^null$' | tr -d \")
-ansible_host=$(echo "$inventory" | jq " ._meta.hostvars[\"$host\"].ansible_host? " | grep -v '^null$' | tr -d \")
+# Except ansible_ssh_common_args and ansible_ssh_extra_args
+ansible_ssh_host=$(echo "$inventory" | jq ".ansible_ssh_host?" | grep -v '^null$' | tr -d \")
+ansible_host=$(echo "$inventory" | jq ".ansible_host?" | grep -v '^null$' | tr -d \")
 # Assign new value if variable is not set or empty
 ansible_host="${ansible_host:-$ansible_ssh_host}"
 # If ansible_host is not set, we should use host name itself
 ansible_host=${ansible_host:-$host}
 $debug && echo "ansible_host: $ansible_host"
 
-ansible_ssh_user=$(echo "$inventory" | jq " ._meta.hostvars[\"$host\"].ansible_ssh_user? " | grep -v '^null$' | tr -d \")
-ansible_user=$(echo "$inventory" | jq " ._meta.hostvars[\"$host\"].ansible_user? " | grep -v '^null$' | tr -d \")
+ansible_ssh_user=$(echo "$inventory" | jq ".ansible_ssh_user?" | grep -v '^null$' | tr -d \")
+ansible_user=$(echo "$inventory" | jq ".ansible_user? " | grep -v '^null$' | tr -d \")
 ansible_user="${ansible_user:-$ansible_ssh_user}"
 $debug && echo "ansible_user: $ansible_user"
 
-ansible_ssh_port=$(echo "$inventory" | jq " ._meta.hostvars[\"$host\"].ansible_ssh_port? " | grep -v '^null$' | tr -d \")
-ansible_port=$(echo "$inventory" | jq " ._meta.hostvars[\"$host\"].ansible_port? " | grep -v '^null$' | tr -d \")
+ansible_ssh_port=$(echo "$inventory" | jq ".ansible_ssh_port?" | grep -v '^null$' | tr -d \")
+ansible_port=$(echo "$inventory" | jq ".ansible_port?" | grep -v '^null$' | tr -d \")
 ansible_port="${ansible_port:-$ansible_ssh_port}"
 $debug && echo "ansible_port: $ansible_port"
 
-ansible_ssh_common_args=$(echo "$inventory" | jq " ._meta.hostvars[\"$host\"].ansible_ssh_common_args? " | grep -v '^null$' | tr -d \")
+ansible_ssh_common_args=$(echo "$inventory" | jq ".ansible_ssh_common_args" | grep -v '^null$' | tr -d \")
 $debug && echo "ansible_ssh_common_args: $ansible_ssh_common_args"
+
+ansible_ssh_extra_args=$(echo "$inventory" | jq ".ansible_ssh_extra_args" | grep -v '^null$' | tr -d \")
+$debug && echo "ansible_ssh_extra_args: $ansible_ssh_extra_args"
 
 # We need to prepend hostname with username@
 if [ -n "$ansible_user" ]; then ansible_user="${ansible_user}@"; fi
@@ -55,5 +65,5 @@ if [ -n "$ansible_user" ]; then ansible_user="${ansible_user}@"; fi
 # If port is set, add it to ssh arguments
 if [ -n "$ansible_port" ]; then ssh_args="$ssh_args -p $ansible_port"; fi
 
-$debug && echo result command: ssh ${ansible_user}${ansible_host} ${ssh_args} ${ansible_ssh_common_args} $@
-exec ssh ${ansible_user}${ansible_host} ${ssh_args} ${ansible_ssh_common_args} $@
+$debug && echo result command: ${ssh_executable} ${ansible_user}${ansible_host} ${ssh_args} ${ansible_ssh_common_args} ${ansible_ssh_extra_args} $@
+exec ${ssh_executable} ${ansible_user}${ansible_host} ${ssh_args} ${ansible_ssh_common_args} ${ansible_ssh_extra_args} $@
